name: dota_heroes
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.5.4 <4.0.0'

dependencies: 
  flutter: 
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  aes256: ^1.0.4
  collection: ^1.18.0
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  envied: ^1.0.0
  equatable: ^2.0.7
  extended_image: ^9.0.7
  flutter_bloc: ^8.1.6
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.0.16
  get_it: ^8.0.2
  go_router: ^14.6.2
  intl: ^0.19.0
  json_annotation: ^4.9.0
  pretty_dio_logger: ^1.4.0
  shared_preferences: ^2.3.3
  uuid: ^4.5.1

dev_dependencies: 
  flutter_lints: ^5.0.0
  flutter_test: 
    sdk: flutter
  build_runner: ^2.4.13
  envied_generator: ^1.0.0
  flutter_gen_runner: ^5.8.0
  json_serializable: ^6.9.0
  mockito: ^5.4.4
  

flutter: 
  uses-material-design: true
  generate: true
  assets:
    - assets/images/

flutter_gen:
  output: lib/generated/
  integrations:
    flutter_svg: true
